
cache:
    directories:
        - $HOME/.cache

jobs:
    include:
        - os: linux
          language: cpp
          script: make && ./configure --disable-doc && make
        - os: osx
          language: cpp
          script: make && ./configure --disable-doc && make
        - os: linux
          language: cpp
          env: BRANCH=3.15
          install: ./.ci/travis-prepare.sh
          script: ./.ci/travis-epics-build.sh
        - os: linux
          language: python
          python: 2.7
          install: pip install nose
          script: python -m nose procServUtils
        - os: linux
          language: python
          python: 3.6
          install: pip install nose
          script: python -m nose procServUtils
